Traceback (most recent call last):
  File "/Users/tomconnolly/programs/miniconda3/envs/data-book/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/tomconnolly/programs/miniconda3/envs/data-book/lib/python3.8/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/tomconnolly/programs/miniconda3/envs/data-book/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/tomconnolly/programs/miniconda3/envs/data-book/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/tomconnolly/programs/miniconda3/envs/data-book/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/tomconnolly/programs/miniconda3/envs/data-book/lib/python3.8/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/Users/tomconnolly/programs/miniconda3/envs/data-book/lib/python3.8/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/tomconnolly/programs/miniconda3/envs/data-book/lib/python3.8/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fvalues = exponential_growth(np.array([0,1]),10,1)
print(fvalues)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m/var/folders/67/t9t76vyd78qgn_kwjr1_76yr0000gn/T/ipykernel_9868/2852909755.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mfvalues[0m [0;34m=[0m [0mexponential_growth[0m[0;34m([0m[0mnp[0m[0;34m.[0m[0marray[0m[0;34m([0m[0;34m[[0m[0;36m0[0m[0;34m,[0m[0;36m1[0m[0;34m][0m[0;34m)[0m[0;34m,[0m[0;36m10[0m[0;34m,[0m[0;36m1[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0mprint[0m[0;34m([0m[0mfvalues[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/var/folders/67/t9t76vyd78qgn_kwjr1_76yr0000gn/T/ipykernel_9868/3487471894.py[0m in [0;36mexponential_growth[0;34m(t, a1, a2)[0m
[1;32m      8[0m     '''
[1;32m      9[0m     [0;31m# insert code here[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 10[0;31m     [0;32mreturn[0m [0mf[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mNameError[0m: name 'f' is not defined
NameError: name 'f' is not defined

